"$schema" = 'https://starship.rs/config-schema.json'

format = """  \ 
$directory$kubernetes$aws$git_branch$git_status
\n    ━▶ \
"""

#right_format = '$kubernetes'
add_newline = true

[character]
disabled = true

[directory]
#style = 'white'
truncation_length = 3
home_symbol = "~"
truncate_to_repo = false

[aws]
format = '(\(aws:[$profile]($style)\)) '
#style = '#ffff36'
style = 'white'

[git_branch]
format = '\([$symbol$branch]($style)\)'
style = '#ffff36'

[git_status]
format = '(\[[$modified$staged]($style)\])'
modified = '*'
style = '#0fc3ff'

[kubernetes]
format = '\(k8s:[$context( \($namespace\))]($style)\) '
#style = '#ffff36'
style = 'white'
disabled = false
